# Generated by Django 5.1.4 on 2024-12-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject',
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
